bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/000.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/001.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/002.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/003.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/004.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/005.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/006.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/007.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/008.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/009.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/010.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/011.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/012.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/013.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/014.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/015.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/016.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/017.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/018.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/019.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/020.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/021.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/022.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/023.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/024.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/025.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/026.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/027.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/028.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/029.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/030.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/031.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/032.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/033.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/034.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/035.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/036.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/037.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/038.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/039.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/040.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/041.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/042.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/043.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/044.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/045.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/046.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/047.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/048.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/049.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/050.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/051.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/052.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/053.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/054.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/055.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/056.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/057.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/058.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/059.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/060.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/061.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/062.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/063.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/064.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/065.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/066.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/067.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/068.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/069.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/070.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/071.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/072.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/073.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/074.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/075.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/076.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/077.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/078.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/079.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/080.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/081.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/082.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/083.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/084.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/085.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/086.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/087.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/088.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/089.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/090.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/091.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/092.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/093.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/094.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/095.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/096.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/097.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/098.txt &
bazel-bin/tensorflow_serving/example/inception_client --server localhost:9000 --image cat.jpg > log/100-cat-concurrent/099.txt &
