# python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. tomtest.proto
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tomtest_pb2 as tomtest__pb2


class OlympianMasterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CallTest = channel.unary_unary(
        '/tensorflow.serving.OlympianMaster/CallTest',
        request_serializer=tomtest__pb2.OlympianRequest.SerializeToString,
        response_deserializer=tomtest__pb2.OlympianReply.FromString,
        )


class OlympianMasterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CallTest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OlympianMasterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CallTest': grpc.unary_unary_rpc_method_handler(
          servicer.CallTest,
          request_deserializer=tomtest__pb2.OlympianRequest.FromString,
          response_serializer=tomtest__pb2.OlympianReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tensorflow.serving.OlympianMaster', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
